<template>
  <the-content-visualization :contentDetails="films" />
</template>

<script>
import TheContentVisualization from "@/components/TheContentVisualization.vue";
export default {
  components: { TheContentVisualization },
  data() {
    return {
      films: [
        {
          id: 819,
          type: "Anime",
          titleOG: "Kakkou No Iinazuke",
          title: "Kakkou No Iinazuke",
          year: 2022,
          note: 8.2,
          language: true,
          favorite: false,
          category: 2,
          info: " ",
          poster:
            "https://firebasestorage.googleapis.com/v0/b/films-a2d18.appspot.com/o/assets%2FKakkou%20No%20Iinazuke%20(2022)?alt=media&token=0fa873ce-239e-49d5-9a66-1d3a7c7a6c7c",
          season: 1,
          link: " ",
          saga: 0,
        },
        {
          id: 786,
          type: "Anime",
          titleOG: "Kimetsu No Yaiba Yuukaku-hen",
          title: "Kimetsu No Yaiba Yuukaku-hen",
          year: 2022,
          note: 9.4,
          language: true,
          favorite: false,
          category: 8,
          info: " ",
          poster:
            "https://firebasestorage.googleapis.com/v0/b/films-a2d18.appspot.com/o/assets%2FKimetsu%20No%20Yaiba%20Yuukaku-hen%20(2022)?alt=media&token=4160e43d-c4f7-45f5-a477-8a9425e4c95a",
          season: 2,
          link: " ",
          saga: 0,
        },
        {
          id: 815,
          type: "Anime",
          titleOG: "Komi-san Wa, Comyushou Desu",
          title: "Komi-san Wa, Comyushou Desu",
          year: 2022,
          note: 9.6,
          language: true,
          favorite: false,
          category: 2,
          info: " ",
          poster:
            "https://firebasestorage.googleapis.com/v0/b/films-a2d18.appspot.com/o/assets%2FKomi-san%20Wa%2C%20Comyushou%20Desu%20(2022)?alt=media&token=de821edc-d323-4769-9962-81f07567e1b8",
          season: 2,
          link: " ",
          saga: 0,
        },
        {
          id: 779,
          type: "Anime",
          titleOG: "Shuumatsu No Harem",
          title: "Shuumatsu No Harem",
          year: 2022,
          note: 8.1,
          language: true,
          favorite: false,
          category: 2,
          info: " ",
          poster:
            "https://firebasestorage.googleapis.com/v0/b/films-a2d18.appspot.com/o/assets%2FShuumatsu%20No%20Harem%20(2022)?alt=media&token=21796033-1045-45d7-92a1-9bfc097e75f2",
          season: 1,
          link: " ",
          saga: 0,
        },
        {
          id: 811,
          type: "Serie",
          titleOG: "Love Death + Robots",
          title: "Love Death + Robots",
          year: 2022,
          note: 9.2,
          language: false,
          favorite: true,
          category: 8,
          info: " ",
          poster:
            "https://firebasestorage.googleapis.com/v0/b/films-a2d18.appspot.com/o/assets%2FLove%20Death%20%2B%20Robots%20(2022)?alt=media&token=ef070439-ffab-4af9-883f-da3fd44e6251",
          season: 3,
          link: " ",
          saga: 0,
        },
        {
          id: 776,
          type: "Anime",
          titleOG: "Sono Bisque Doll Wa Koi Wo Suru",
          title: "Sono Bisque Doll Wa Koi Wo Suru",
          year: 2022,
          note: 8.5,
          language: true,
          favorite: false,
          category: 2,
          info: " ",
          poster:
            "https://firebasestorage.googleapis.com/v0/b/films-a2d18.appspot.com/o/assets%2FSono%20Bisque%20Doll%20Wa%20Koi%20Wo%20Suru%20(2022)?alt=media&token=c96ed214-b5cf-41da-8705-d0e57cd119f8",
          season: 1,
          link: " ",
          saga: 0,
        },
        {
          id: 818,
          type: "Anime",
          titleOG: "Spy × Family",
          title: "Spy × Family",
          year: 2022,
          note: 9.6,
          language: true,
          favorite: false,
          category: 5,
          info: " ",
          poster:
            "https://firebasestorage.googleapis.com/v0/b/films-a2d18.appspot.com/o/assets%2FSpy%20%C3%97%20Family%20(2022)?alt=media&token=e4225845-4296-41bb-a4b0-75aa454d2ccc",
          season: 1,
          link: " ",
          saga: 0,
        },
        {
          id: 816,
          type: "Movie",
          titleOG: "Doctor Strange In The Multiverse Of Madness",
          title: "Doctor Strange En El Multiverso De La Locura",
          year: 2022,
          note: 8.6,
          language: false,
          favorite: false,
          category: 5,
          info: " ",
          poster:
            "https://firebasestorage.googleapis.com/v0/b/films-a2d18.appspot.com/o/assets%2FDoctor%20Strange%20In%20The%20Multiverse%20Of%20Madness%20(2022)?alt=media&token=c6a6f840-7e32-41d1-8cb1-c80f961dafdb",
          season: 0,
          link: " ",
          saga: 1,
        },
        {
          id: 817,
          type: "Anime",
          titleOG: "Tate No Yuusha No Nariagari",
          title: "The Rising Of The Shield Hero",
          year: 2022,
          note: 7.6,
          language: true,
          favorite: false,
          category: 8,
          info: " ",
          poster:
            "https://firebasestorage.googleapis.com/v0/b/films-a2d18.appspot.com/o/assets%2FTate%20No%20Yuusha%20No%20Nariagari%20(2022)?alt=media&token=e097aa04-3da6-473e-bacb-67aa6db79f64",
          season: 2,
          link: " ",
          saga: 0,
        },
        {
          id: 787,
          type: "Movie",
          titleOG: "Batman",
          title: "The Batman",
          year: 2022,
          note: 8.2,
          language: false,
          favorite: false,
          category: 5,
          info: " ",
          poster:
            "https://firebasestorage.googleapis.com/v0/b/films-a2d18.appspot.com/o/assets%2FBatman%20(2022)?alt=media&token=84fab9e5-e599-4cfa-954a-6b3447182ca2",
          season: 0,
          link: " ",
          saga: 2,
        },
        {
          id: 766,
          type: "Movie",
          titleOG: "A Través De Mi Ventana",
          title: "A Través De Mi Ventana",
          year: 2022,
          note: 7.2,
          language: true,
          favorite: false,
          category: 2,
          info: " ",
          poster:
            "https://firebasestorage.googleapis.com/v0/b/films-a2d18.appspot.com/o/assets%2FA%20Trav%C3%A9s%20De%20Mi%20Ventana%20(2022)?alt=media&token=bcc35e7f-a751-4b2c-88ff-f4200bf8b731",
          season: 0,
          link: " ",
          saga: 0,
        },
        {
          id: 677,
          type: "Movie",
          titleOG: "The Conjuring: The Devil Made Me Do It",
          title: "El Conjuro 3",
          year: 2021,
          note: 8,
          language: false,
          favorite: false,
          category: 14,
          info: " ",
          poster:
            "https://firebasestorage.googleapis.com/v0/b/films-a2d18.appspot.com/o/assets%2FThe%20Conjuring%203%20The%20Devil%20Made%20Me%20Do%20It%20(2021).webp?alt=media&token=8d1b33ba-e893-49a4-a692-6aa83df66dc6",
          season: 0,
          link: " ",
          saga: 8,
        },
        {
          id: 674,
          type: "Movie",
          titleOG: "Chaos Walking",
          title: "Caos El Inicio",
          year: 2021,
          note: 7.6,
          language: false,
          favorite: false,
          category: 10,
          info: " ",
          poster:
            "https://firebasestorage.googleapis.com/v0/b/films-a2d18.appspot.com/o/assets%2FChaos%20Walking%20(2021).webp?alt=media&token=3c3066a6-c587-4ac2-a979-db4306902eef",
          season: 0,
          link: " ",
          saga: 0,
        },
        {
          id: 673,
          type: "Movie",
          titleOG: "Godzilla Vs Kong",
          title: "Godzilla Vs Kong",
          year: 2021,
          note: 8.6,
          language: false,
          favorite: false,
          category: 10,
          info: " ",
          poster:
            "https://firebasestorage.googleapis.com/v0/b/films-a2d18.appspot.com/o/assets%2FGodzilla%20Vs%20Kong%20(2021)?alt=media&token=8d92ef15-6996-40d6-b099-7aba903f83ae",
          season: 0,
          link: " ",
          saga: 14,
        },
        {
          id: 671,
          type: "Movie",
          titleOG: "승리호",
          title: "Barrenderos Espaciales",
          year: 2021,
          note: 8.2,
          language: false,
          favorite: false,
          category: 10,
          info: " ",
          poster:
            "https://firebasestorage.googleapis.com/v0/b/films-a2d18.appspot.com/o/assets%2FSpace%20Sweepers%20(2021).webp?alt=media&token=12deac23-48fb-4fbe-84bf-1bf93d22ccf0",
          season: 0,
          link: " ",
          saga: 0,
        },
        {
          id: 678,
          type: "Movie",
          titleOG: "Cruella",
          title: "Cruella",
          year: 2021,
          note: 8.5,
          language: false,
          favorite: false,
          category: 11,
          info: " ",
          poster:
            "https://firebasestorage.googleapis.com/v0/b/films-a2d18.appspot.com/o/assets%2FCruella%20(2021).webp?alt=media&token=f154dce7-7476-4f4d-bc1e-0aebfb340716",
          season: 0,
          link: " ",
          saga: 0,
        },
        {
          id: 672,
          type: "Movie",
          titleOG: "Zack Snyder's Justice League",
          title: "La Liga de la Justicia de Zack Snyder",
          year: 2021,
          note: 10,
          language: false,
          favorite: false,
          category: 10,
          info: " ",
          poster:
            "https://firebasestorage.googleapis.com/v0/b/films-a2d18.appspot.com/o/assets%2FZack%20Snyder's%20Justice%20League%20(2021).webp?alt=media&token=471f5386-a559-41fe-a426-0237c553e052",
          season: 0,
          link: " ",
          saga: 2,
        },
        {
          id: 670,
          type: "Movie",
          titleOG: "Raya And The Last Dragon",
          title: "Raya Y El Ultimo Dragon",
          year: 2021,
          note: 8.1,
          language: false,
          favorite: false,
          category: 6,
          info: " ",
          poster:
            "https://firebasestorage.googleapis.com/v0/b/films-a2d18.appspot.com/o/assets%2FRaya%20and%20the%20Last%20Dragon%20(2021).webp?alt=media&token=3c298cc8-f2a7-4349-b21c-bfece4feb491",
          season: 0,
          link: " ",
          saga: 3,
        },
        {
          id: 722,
          type: "Anime",
          titleOG: "死神坊ちゃんと黒メイド",
          title: "Shinigami Bocchan To Kuro Maid",
          year: 2021,
          note: 8.4,
          language: true,
          favorite: false,
          category: 2,
          info: " ",
          poster:
            "https://firebasestorage.googleapis.com/v0/b/films-a2d18.appspot.com/o/assets%2FShinigami%20Bocchan%20to%20Kuro%20Maid%20(2021).webp?alt=media&token=813192a3-1695-4eea-8d9c-b6a6cfb4d2ee",
          season: 1,
          link: " ",
          saga: 0,
        },
        {
          id: 753,
          type: "Serie",
          titleOG: "WandaVision",
          title: "WandaVision",
          year: 2021,
          note: 9,
          language: false,
          favorite: false,
          category: 0,
          info: " ",
          poster:
            "https://firebasestorage.googleapis.com/v0/b/films-a2d18.appspot.com/o/assets%2FWandaVision%20(2021).webp?alt=media&token=d30a6cba-f863-4e61-a7e0-6278c3783eb5",
          season: 1,
          link: " ",
          saga: 1,
        },
        {
          id: 721,
          type: "Anime",
          titleOG: "Seirei Gensōki",
          title: "Seirei Gensouki",
          year: 2021,
          note: 9.1,
          language: true,
          favorite: true,
          category: 8,
          info: " ",
          poster:
            "https://firebasestorage.googleapis.com/v0/b/films-a2d18.appspot.com/o/assets%2FSeirei%20Gensoki%20(2021).webp?alt=media&token=97b9fe07-204f-4a14-a9bc-88555faa96ac",
          season: 1,
          link: " ",
          saga: 0,
        },
        {
          id: 719,
          type: "Anime",
          titleOG: "ワンダーエッグ・プライオリティ",
          title: "Wonder Egg Priority",
          year: 2021,
          note: 9.2,
          language: true,
          favorite: false,
          category: 8,
          info: " ",
          poster:
            "https://firebasestorage.googleapis.com/v0/b/films-a2d18.appspot.com/o/assets%2FWonder%20Egg%20Priority%20(2021).webp?alt=media&token=4dd2c037-0faf-45f6-9f0c-ce6f848d911b",
          season: 1,
          link: " ",
          saga: 0,
        },
        {
          id: 757,
          type: "Serie",
          titleOG: "The Falcon And The Winter Soldier",
          title: "Falcon Y El Soldado Del Invierno",
          year: 2021,
          note: 8.8,
          language: false,
          favorite: false,
          category: 10,
          info: " ",
          poster:
            "https://firebasestorage.googleapis.com/v0/b/films-a2d18.appspot.com/o/assets%2FThe%20Falcon%20and%20the%20Winter%20Soldier%20(2021).webp?alt=media&token=aaf3e2c5-6940-4606-84fe-3e7ff70c04bd",
          season: 1,
          link: " ",
          saga: 1,
        },
        {
          id: 756,
          type: "Serie",
          titleOG: "Formula 1 Drive To Survive",
          title: "Formula 1 Drive To Survive",
          year: 2021,
          note: 8.5,
          language: true,
          favorite: false,
          category: 0,
          info: " ",
          poster:
            "https://firebasestorage.googleapis.com/v0/b/films-a2d18.appspot.com/o/assets%2FFormula%201%20Drive%20to%20Survive%20(2021).webp?alt=media&token=0cfd4a09-91e9-4002-94a1-69f0815c3446",
          season: 3,
          link: " ",
          saga: 0,
        },
        {
          id: 720,
          type: "Anime",
          titleOG: "ぼくたちのリメイク",
          title: "Bokutachi No Remake",
          year: 2021,
          note: 8.7,
          language: true,
          favorite: false,
          category: 1,
          info: " ",
          poster:
            "https://firebasestorage.googleapis.com/v0/b/films-a2d18.appspot.com/o/assets%2FBokutachi%20no%20Remake%20(2021).webp?alt=media&token=4720e8f1-a075-474e-aa71-e700c17b62b6",
          season: 1,
          link: " ",
          saga: 0,
        },
        {
          id: 679,
          type: "Movie",
          titleOG: "Oxygéne",
          title: "Oxígeno",
          year: 2021,
          note: 7.8,
          language: true,
          favorite: false,
          category: 1,
          info: " ",
          poster:
            "https://firebasestorage.googleapis.com/v0/b/films-a2d18.appspot.com/o/assets%2FOxygen%20(2021).webp?alt=media&token=6705589a-9ff3-4455-818f-8bd6b46167bb",
          season: 0,
          link: " ",
          saga: 0,
        },
        {
          id: 709,
          type: "Anime",
          titleOG: "Gotoubun No Hanayome",
          title: "Gotoubun No Hanayome",
          year: 2021,
          note: 8.8,
          language: true,
          favorite: false,
          category: 2,
          info: " ",
          poster:
            "https://firebasestorage.googleapis.com/v0/b/films-a2d18.appspot.com/o/assets%2FGotoubun%20No%20Hanayome%20(2021).webp?alt=media&token=fe20f0ea-6dda-4bd3-b312-f5e025fb831b",
          season: 2,
          link: " ",
          saga: 0,
        },
        {
          id: 714,
          type: "Anime",
          titleOG: "Mushoku Tensei Isekai Ittara Honki Dasu",
          title: "Mushoku Tensei Isekai Ittara Honki Dasu",
          year: 2021,
          note: 9.5,
          language: true,
          favorite: false,
          category: 8,
          info: " ",
          poster:
            "https://firebasestorage.googleapis.com/v0/b/films-a2d18.appspot.com/o/assets%2FMushoku%20Tensei%20Isekai%20Ittara%20Honki%20Dasu%20(2021).webp?alt=media&token=d5f3a849-ad02-4d85-a7ea-d48806ad7bf6",
          season: 1,
          link: " ",
          saga: 0,
        },
        {
          id: 708,
          type: "Anime",
          titleOG: "Hori-san To Miyamura-kun",
          title: "Horimiya",
          year: 2021,
          note: 8.5,
          language: true,
          favorite: false,
          category: 2,
          info: " ",
          poster:
            "https://firebasestorage.googleapis.com/v0/b/films-a2d18.appspot.com/o/assets%2FHori-San%20To%20Miyamura-Kun%20(2021).webp?alt=media&token=972c4e0c-ddfd-4040-9663-c3da2a529b7a",
          season: 1,
          link: " ",
          saga: 0,
        },
        {
          id: 691,
          type: "Movie",
          titleOG: "Free Guy",
          title: "Free Guy",
          year: 2021,
          note: 8.2,
          language: false,
          favorite: false,
          category: 3,
          info: " ",
          poster:
            "https://firebasestorage.googleapis.com/v0/b/films-a2d18.appspot.com/o/assets%2FFree%20Guy%20(2021).webp?alt=media&token=161f74a1-8b0d-43af-92c1-00a85e328259",
          season: 0,
          link: " ",
          saga: 0,
        },
      ],
    };
  },
};
</script>

<style></style>
